# Usamos Node LTS para estabilidad [cite: 3]
FROM node:lts-alpine3.22

WORKDIR /app/frontend

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]