version: "3.9"

services:
  envios_db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: enviosAdmin
      POSTGRES_PASSWORD: express123
      POSTGRES_DB: sistema_envios
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - red_db
    expose:
      - "5432"

  ldap:
    build:
      context: ./ldap
      dockerfile: dockerfile.dev
    container_name: ldap-envios
    restart: unless-stopped
    environment:
      LDAP_ORGANISATION: "envios"
      LDAP_DOMAIN: "envios.local"
      LDAP_ADMIN_PASSWORD: "admin123"
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d
    networks:
      - red_ldap

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile.dev
    ports:
      - "80:80"
      - "443:443"
    networks:
      - red_publica
      - red_apps
    depends_on:
      - servidor
      - ldap

  servidor:
    build:
      context: ./servidor/backend
      dockerfile: Dockerfile.dev
    networks:
      - red_apps
      - red_db
      - red_ldap
    depends_on:
      - envios_db
      - ldap

  mostrador:
    build:
      context: ./mostrador
      dockerfile: Dockerfile.dev
    tty: true
    stdin_open: true
    networks:
      - red_apps
      - red_ldap
    depends_on:
      - ldap

  despachador:
  build:
    context: ./despachador
    dockerfile: Dockerfile.dev
    tty: true
    stdin_open: true
    networks:
      - red_apps
      - red_ldap
    depends_on:
      - ldap

  atencion_cliente:
    build:
      context: ./atencion_cliente
      dockerfile: Dockerfile.dev
    tty: true
    stdin_open: true
    networks:
      - red_apps
      - red_ldap

networks:
  red_publica:
    driver: bridge
  red_apps:
    driver: bridge
  red_db:
    driver: bridge
  red_ldap:
    driver: bridge

volumes:
  ldap_data:
  ldap_config:
